export const TAKE_INTERNS = "TAKE_INTERNS";
export const TAKE_INTERNS_FAILED = "TAKE_INTERNS_FAILED";

export const ADD_INTERN = "ADD_INTERN";
export const ADD_INTERN_FAILED = "ADD_INTERN_FAILED";

export const UPDATE_INTERN = "UPDATE_INTERN";
export const UPDATE_INTERN_FAILED = "UPDATE_INTERN_FAILED";

export const DELETE_INTERN = "DELETE_INTERN";
export const DELETE_INTERN_FAILED = "DELETE_INTERN_FAILED";

export const EDIT_INTERN = "EDIT_INTERN";

export const LOGIN_USER = "LOGIN_USER";
